<a href="https://colab.research.google.com/github/a3s0h/numpy.py/blob/main/numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
ar = np.array([1,2])
print(ar) # this is a vector

[1 2]


In [3]:
are = np.array([[1,2,3],[3,4,6]])
print(are) # metrics

[[1 2 3]
 [3 4 6]]


In [4]:
c = np.array([[[1,2],[4,3],[6,5]]])
print(c) # tensor (3D array)

[[[1 2]
  [4 3]
  [6 5]]]


In [5]:
# creating with different  dtype
# np.array([1,2,3],dtype=float)
# np.array([1,2,3],dtype=bool)
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [6]:
# arange (to create an array in a range)
# np.arange(1,11) # 1 to 10
np.arange(1,11,2)  # 1 to 10 with gap of 2

array([1, 3, 5, 7, 9])

In [7]:
# rehape
np.arange(1,11).reshape(2,5) # 2 rows , 5 cols      note: rows * cols <= number of elements 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])


# **Initailizing array**:

In [8]:
# np.ones and np .zeros
np.ones((3,4))  # used to give initial weights to the neural network nodes 
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
# np.random
np.random.random((3,4))

array([[0.41773551, 0.29424975, 0.17519258, 0.1389969 ],
       [0.23568906, 0.8250968 , 0.21004407, 0.11381621],
       [0.39230411, 0.30227467, 0.3383714 , 0.8933795 ]])

In [10]:
#np.linspace : genrates points with equal distance in a given range 
np.linspace(-10,10,10)     # (lower range,upper range,number of items)
# uses : used in plotting

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [11]:
# np.identity  : creates identity mertics (diagal elements  = 1's, rest all are 0's)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## **Attributes**

In [12]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8,dtype=float).reshape(2,2,2)

a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# ndim : for dimension
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [14]:
# shape : tells no. of rows and cols in a dimension
a1.shape,a2.shape,a3.shape    # a1 has 10 items , a2 has 3 rows and 4 cols , a3 has two 2d array with 2 rows and 2 cols each


((10,), (3, 4), (2, 2, 2))

In [15]:
# size : gives no. of items
a1.size,a2.size,a3.size

(10, 12, 8)

In [16]:
#itemsize
a1.itemsize,a2.itemsize,a3.itemsize      # by default in collab all dtypes have same size (try with others IDEs)
# to resolve this give a dtype while initializnig array 
# int32 -> 4
# int64,float -> 8

(8, 8, 8)

In [17]:
# dtype 
a1.dtype,a2.dtype,a3.dtype

(dtype('int64'), dtype('float64'), dtype('float64'))

# **Changing the data types **

In [18]:
a3.dtype


dtype('float64')

In [19]:
# uses: to reduce the size when we are sure that we can handle that data type with a smaller one too 
a3.astype(np.int32) 

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

# **Array Operations**
1> scaler operations
2> vectore operations

In [20]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [21]:
# scaler operations

# arithematic 
a1*2     # every element is multiplies with 2 , can use any operations like +,-,/  etc

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [22]:
# relationsla operators 
a2>15  # compare with every element

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [23]:
# vector operations : apllying operations on two np arrays
# arthematic
a1+a2   # can do for any operator 

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

# **Array Functions**

In [24]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[72., 20., 33.],
       [22., 42., 89.],
       [ 3.,  4., 19.]])

In [25]:
# min/max/sum/prod
np.max(a1),np.min(a1),np.sum(a1),np.prod(a1)

(89.0, 3.0, 304.0, 890990876160.0)

In [26]:
# finding min for every row
np.min(a1,axis=0) 
# for column
np.min(a1,axis=1)
np.sum(a1,axis=1)   # sum of all cols 

array([125., 153.,  26.])

In [27]:
# mean/median/std/var

In [28]:
np.mean(a1)

33.77777777777778

In [29]:
np.mean(a1,axis=1)  

array([41.66666667, 51.        ,  8.66666667])

In [30]:
# trignometric fns
np.sin(a1)

array([[ 0.25382336,  0.91294525,  0.99991186],
       [-0.00885131, -0.91652155,  0.86006941],
       [ 0.14112001, -0.7568025 ,  0.14987721]])

In [31]:
# dot product 
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

In [32]:
# log and exponents
np.log(a1),np.exp(a1)

(array([[4.27666612, 2.99573227, 3.49650756],
        [3.09104245, 3.73766962, 4.48863637],
        [1.09861229, 1.38629436, 2.94443898]]),
 array([[1.85867175e+31, 4.85165195e+08, 2.14643580e+14],
        [3.58491285e+09, 1.73927494e+18, 4.48961282e+38],
        [2.00855369e+01, 5.45981500e+01, 1.78482301e+08]]))

In [36]:
# round / floor / ceil

np.round(np.random.random((2,3))*100)
np.floor(np.random.random((2,3))*100)
np.ceil(np.random.random((2,3))*100)

array([[27., 54., 52.],
       [93., 92., 27.]])

# **Indexing and slicing**

In [37]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8,dtype=float).reshape(2,2,2)

In [38]:
# indexing
a1


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
a1[0],a1[-1] # first element and last element

(0, 9)

In [41]:
# indexing for 2d array
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [42]:
a2[1,2]       # in first row and at which column

6.0

In [43]:
# last item
a2[-1,-1]

11.0

In [44]:
# indexing in 3d array / tensor
a3

array([[[0., 1.],
        [2., 3.]],

       [[4., 5.],
        [6., 7.]]])

In [45]:
# accessing '5' 
a3[1,0,1]        # [which array(for eg, 5 is in 2nd array of this 3d tensor),which row ,which column]

5.0

In [46]:
# accessing '2'
a3[0,1,0]

2.0

In [47]:
# slicing in 1d
a1
# access 2,3,4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
a1[2:5]

array([2, 3, 4])

In [49]:
# slicing in 2d
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [50]:
# slcing first row
a2[0,:]      # [0rth row , all clomuns]

array([0., 1., 2., 3.])

In [51]:
# 3rd column
a2[:,2]  # [all rows,3rd column]

array([ 2.,  6., 10.])

In [56]:
# access 5,6,9,10 from a2
a2[1:,1:3]        # [1 onwards , 1st to 2nd col(excluding 3rd)]

array([[ 5.,  6.],
       [ 9., 10.]])

In [57]:
# access 0,3,8,11 from a2
a2[::2,::3]         # just like slicing 
# slicing in row -> ::2 means from 0 to next all rows with the jump of 2
# slicing in cols -> ::2 means from 0 to next all cols with the jump of 3

array([[ 0.,  3.],
       [ 8., 11.]])

In [58]:
# access 1,3,9,11 from a2
a2[::2,1::2]

array([[ 1.,  3.],
       [ 9., 11.]])

In [59]:
# access 4,7 from a2
a2[1,::3]

array([4., 7.])

In [62]:
# access 1,2,3,5,6,7 from a2
a2[:2,1:]

array([[1., 2., 3.],
       [5., 6., 7.]])

In [66]:
# slicing in 3d array
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [68]:
# access 2nd 2d array (i.e., 9,10,11.....) from a3
a3[1]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [69]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [71]:
# access 2nd row of 1st 2d array  from a3
a3[0,1,:]

array([3, 4, 5])

In [73]:
# access 2nd col of 2nd 2d array  from a3
a3[1,:,1]

array([10, 13, 16])

In [74]:
# access 22,23,25,26  from a3
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [75]:
# access 0,2,18,20  from a3
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

# **Iterating**

In [76]:
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [85]:
for i in a2:
  print(i)

[0. 1. 2. 3.]
[4. 5. 6. 7.]
[ 8.  9. 10. 11.]


In [86]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [87]:
# iterating every item in a3
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# **reshaping**

In [88]:
# transpose
np.transpose(a2)

array([[ 0.,  4.,  8.],
       [ 1.,  5.,  9.],
       [ 2.,  6., 10.],
       [ 3.,  7., 11.]])

In [89]:
# ravel    : converts array into 1-d array
a2.ravel()

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

# **Stacking**
joining / concatinating multiple arrays, 
shape must be same(Note)

In [94]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [96]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [97]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [95]:
# horizonatl stack
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [98]:
# vertical stack
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# **Splitting**

In [99]:
# horizontal split
np.hsplit(a4,2)  # (array , number of equal parts to make )

[array([[0, 1],
        [4, 5],
        [8, 9]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [100]:
# vertical split
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [101]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]