<a href="https://colab.research.google.com/github/a3s0h/numpy.py/blob/main/numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
ar = np.array([1,2])
print(ar) # this is a vector

[1 2]


In [6]:
are = np.array([[1,2,3],[3,4,6]])
print(are) # metrics

[[1 2 3]
 [3 4 6]]


In [7]:
c = np.array([[[1,2],[4,3],[6,5]]])
print(c) # tensor (3D array)

[[[1 2]
  [4 3]
  [6 5]]]


In [10]:
# creating with different  dtype
# np.array([1,2,3],dtype=float)
# np.array([1,2,3],dtype=bool)
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [14]:
# arange (to create an array in a range)
# np.arange(1,11) # 1 to 10
np.arange(1,11,2)  # 1 to 10 with gap of 2

array([1, 3, 5, 7, 9])

In [23]:
# rehape
np.arange(1,11).reshape(2,5) # 2 rows , 5 cols      note: rows * cols <= number of elements 

ValueError: ignored


# **Initailizing array**:

In [19]:
# np.ones and np .zeros
np.ones((3,4))  # used to give initial weights to the neural network nodes 
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
# np.random
np.random.random((3,4))

array([[0.42644555, 0.21254819, 0.57092791, 0.51322486],
       [0.24548656, 0.45400343, 0.29209495, 0.83014974],
       [0.77982449, 0.62837728, 0.7482722 , 0.61442815]])

In [21]:
#np.linspace : genrates points with equal distance in a given range 
np.linspace(-10,10,10)     # (lower range,upper range,number of items)
# uses : used in plotting

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [22]:
# np.identity  : creates identity mertics (diagal elements  = 1's, rest all are 0's)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## **Attributes**

In [32]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8,dtype=float).reshape(2,2,2)

a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
# ndim : for dimension
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [31]:
# shape : tells no. of rows and cols in a dimension
a1.shape,a2.shape,a3.shape    # a1 has 10 items , a2 has 3 rows and 4 cols , a3 has two 2d array with 2 rows and 2 cols each


((10,), (3, 4), (2, 2, 2))

In [34]:
# size : gives no. of items
a1.size,a2.size,a3.size

(10, 12, 8)

In [35]:
#itemsize
a1.itemsize,a2.itemsize,a3.itemsize      # by default in collab all dtypes have same size (try with others IDEs)
# to resolve this give a dtype while initializnig array 
# int32 -> 4
# int64,float -> 8

(8, 8, 8)

In [36]:
# dtype 
a1.dtype,a2.dtype,a3.dtype

(dtype('int64'), dtype('float64'), dtype('float64'))

# **Changing the data types **

In [37]:
a3.dtype


dtype('float64')

In [38]:
# uses: to reduce the size when we are sure that we can handle that data type with a smaller one too 
a3.astype(np.int32) 

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

# **Array Operations**
1> scaler operations
2> vectore operations

In [39]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [40]:
# scaler operations

# arithematic 
a1*2     # every element is multiplies with 2 , can use any operations like +,-,/  etc

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [43]:
# relationsla operators 
a2>15  # compare with every element

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [44]:
# vector operations : apllying operations on two np arrays
# arthematic
a1+a2   # can do for any operator 

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

# **Array Functions**

In [45]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[55.,  7., 46.],
       [17., 59., 59.],
       [65., 19., 35.]])

In [48]:
# min/max/sum/prod
np.max(a1),np.min(a1),np.sum(a1),np.prod(a1)

(65.0, 7.0, 362.0, 45300866360750.0)

In [52]:
# finding min for every row
np.min(a1,axis=0) 
# for column
np.min(a1,axis=1)
np.sum(a1,axis=1)   # sum of all cols 

array([108., 135., 119.])

In [53]:
# mean/median/std/var

In [54]:
np.mean(a1)

40.22222222222222

In [55]:
np.mean(a1,axis=1)  

array([36.        , 45.        , 39.66666667])

In [56]:
# trignometric fns
np.sin(a1)

array([[-0.99975517,  0.6569866 ,  0.90178835],
       [-0.96139749,  0.63673801,  0.63673801],
       [ 0.82682868,  0.14987721, -0.42818267]])

In [58]:
# dot product 
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)