<a href="https://colab.research.google.com/github/a3s0h/numpy.py/blob/main/session_15_numpy_tricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **in numpy: **
# **axis=0 -> column**
# **axis=1 -> row**

### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [2]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([ 1, 89, 70, 22, 11, 99, 51, 69, 49, 27, 33, 30, 96,  1, 73])

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[19,  6, 64, 52],
       [51, 45, 88, 98],
       [97, 15, 64, 71],
       [43, 38, 69, 77],
       [71, 82,  6, 33],
       [60, 14, 92,  4]])

In [62]:
np.sort(a)
# np.sort(a)[::-1]      # for sorting in descending order

array([  1,  11,  22,  27,  30,  33,  49,  51,  69,  70,  73,  96,  99,
       110, 530])

In [66]:
# np.sort(b)  # this will sort row-wise
np.sort(b,axis=0)    # column wise

array([[19,  6,  6,  4],
       [43, 14, 64, 33],
       [51, 15, 64, 52],
       [60, 38, 69, 71],
       [71, 45, 88, 77],
       [97, 82, 92, 98]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [5]:
# code
np.append(a,200)        # append '200' at last

array([  1,  89,  70,  22,  11,  99,  51,  69,  49,  27,  33,  30,  96,
         1,  73, 200])

In [6]:
b

array([[19,  6, 64, 52],
       [51, 45, 88, 98],
       [97, 15, 64, 71],
       [43, 38, 69, 77],
       [71, 82,  6, 33],
       [60, 14, 92,  4]])

In [69]:
b.shape

(6, 4)

In [77]:
np.append(b,np.ones((b.shape[0],1)),axis=1) # adding one more column with value "1"
# np.append(b,np.ones((1,b.shape[1])),axis=0)      # adding one more row with value "1"
# np.append(b,np.random.random((b.shape[0],1)),axis=1)   # appeding random values 

array([[19.,  6., 64., 52.,  1.],
       [51., 45., 88., 98.,  1.],
       [97., 15., 64., 71.,  1.],
       [43., 38., 69., 77.,  1.],
       [71., 82.,  6., 33.,  1.],
       [60., 14., 92.,  4.,  1.]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [8]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [9]:
np.concatenate((c,d),axis=0)      # vertical

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
np.concatenate((c,d),axis=1) # horizontal

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [11]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [12]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [13]:
# code
a.shape

(15,)

In [79]:
np.expand_dims(a,axis=0)

array([[110, 530,  70,  22,  11,  99,  51,  69,  49,  27,  33,  30,  96,
          1,  73]])

In [14]:
np.expand_dims(a,axis=0).shape     # 1D ->  2D 

(1, 15)

In [80]:
np.expand_dims(a,axis=1)

array([[110],
       [530],
       [ 70],
       [ 22],
       [ 11],
       [ 99],
       [ 51],
       [ 69],
       [ 49],
       [ 27],
       [ 33],
       [ 30],
       [ 96],
       [  1],
       [ 73]])

In [78]:
np.expand_dims(a,axis=1).shape

(15, 1)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [16]:
a

array([ 1, 89, 70, 22, 11, 99, 51, 69, 49, 27, 33, 30, 96,  1, 73])

In [17]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 1,  2,  5,  6,  7, 12, 14]),)

In [18]:
# now replace all values > 50 with 0
np.where(a>50,0,a)         # .where(condition,True,False)   is condition met then replace with 0 else pass

array([ 1,  0,  0, 22, 11,  0,  0,  0, 49, 27, 33, 30,  0,  1,  0])

In [19]:
# replace even numbers with 0
np.where(a%2 == 0,0,a)

array([ 1, 89,  0,  0, 11, 99, 51, 69, 49, 27, 33,  0,  0,  1, 73])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [20]:
# code
a

array([ 1, 89, 70, 22, 11, 99, 51, 69, 49, 27, 33, 30, 96,  1, 73])

In [21]:
np.argmax(a)       # returns the index of maximum element 

5

In [22]:
b

array([[19,  6, 64, 52],
       [51, 45, 88, 98],
       [97, 15, 64, 71],
       [43, 38, 69, 77],
       [71, 82,  6, 33],
       [60, 14, 92,  4]])

In [23]:
np.argmax(b,axis=0)     # max element's index in column

array([2, 4, 5, 1])

In [24]:
np.argmax(b,axis=1)       # max element's index in row

array([2, 3, 0, 3, 1, 2])

In [25]:
# np.argmin
np.argmin(a)

0

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [26]:
a

array([ 1, 89, 70, 22, 11, 99, 51, 69, 49, 27, 33, 30, 96,  1, 73])

In [27]:
np.cumsum(a)       # cummulitive sum -> 1 , 1+89=90 , 90+70=160 ............

array([  1,  90, 160, 182, 193, 292, 343, 412, 461, 488, 521, 551, 647,
       648, 721])

In [28]:
b

array([[19,  6, 64, 52],
       [51, 45, 88, 98],
       [97, 15, 64, 71],
       [43, 38, 69, 77],
       [71, 82,  6, 33],
       [60, 14, 92,  4]])

In [82]:
np.cumsum(b,axis=0)      # for column 

array([[ 19,   6,  64,  52],
       [ 70,  51, 152, 150],
       [167,  66, 216, 221],
       [210, 104, 285, 298],
       [281, 186, 291, 331],
       [341, 200, 383, 335]])

In [84]:
np.cumsum(b,axis=1)      # for row

array([[ 19,  25,  89, 141],
       [ 51,  96, 184, 282],
       [ 97, 112, 176, 247],
       [ 43,  81, 150, 227],
       [ 71, 153, 159, 192],
       [ 60,  74, 166, 170]])

In [30]:
np.cumsum(b)      # if no axis is provided then it will convert it into 1d array

array([  19,   25,   89,  141,  192,  237,  325,  423,  520,  535,  599,
        670,  713,  751,  820,  897,  968, 1050, 1056, 1089, 1149, 1163,
       1255, 1259])

In [31]:
# np.cumprod for product
np.cumprod(a)

array([                   1,                   89,                 6230,
                     137060,              1507660,            149258340,
                 7612175340,         525240098460,       25736764824540,
            694892650262580,    22931457458665140,   687943723759954200,
       -7744378813882603264, -7744378813882603264,  6509412871566061824])

In [32]:
a

array([ 1, 89, 70, 22, 11, 99, 51, 69, 49, 27, 33, 30, 96,  1, 73])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis. 

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

Percentile = (Number of Values Below “x” / Total Number of Values) × 100

In [88]:
a

array([110, 530,  70,  22,  11,  99,  51,  69,  49,  27,  33,  30,  96,
         1,  73])

In [89]:
np.percentile(a,100)        # calculates 100 percentile . i.e., the number whihc is maximum 

530.0

In [86]:
np.percentile(a,0)     # the number whihc is smallest 

1.0

In [90]:
np.percentile(a,50)         # the number which is above 50% of the numbers in a 

51.0

In [35]:
np.median(a)

49.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [36]:
# code
a

array([ 1, 89, 70, 22, 11, 99, 51, 69, 49, 27, 33, 30, 96,  1, 73])

In [92]:
# returns frequency count in given range
# np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])    # (bins -> bin size , here it's returning number of items in 0-10 ,10-20,30-40 ....)
np.histogram(a,bins=[0,50,100])

(array([7, 6]), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

corelation ranges btw -1 to 1 . if correlation is 0 then no relations . if 1 then relation is proprtional / positivly corelated . if -1 then inversly proportional / negatively corelated 

In [38]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)
# this calculates corelation btw salary and salary , salary and experience , expereince and salary and expereience and experience 


array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [93]:
# code
a


array([110, 530,  70,  22,  11,  99,  51,  69,  49,  27,  33,  30,  96,
         1,  73])

In [94]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([70, 30])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [41]:
# code
a

array([ 1, 89, 70, 22, 11, 99, 51, 69, 49, 27, 33, 30, 96,  1, 73])

In [42]:
np.flip(a)

array([73,  1, 96, 30, 33, 27, 49, 69, 51, 99, 11, 22, 70, 89,  1])

In [43]:
b

array([[19,  6, 64, 52],
       [51, 45, 88, 98],
       [97, 15, 64, 71],
       [43, 38, 69, 77],
       [71, 82,  6, 33],
       [60, 14, 92,  4]])

In [44]:
np.flip(b,axis=1)

array([[52, 64,  6, 19],
       [98, 88, 45, 51],
       [71, 64, 15, 97],
       [77, 69, 38, 43],
       [33,  6, 82, 71],
       [ 4, 92, 14, 60]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array. 

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [45]:
# code
a

array([ 1, 89, 70, 22, 11, 99, 51, 69, 49, 27, 33, 30, 96,  1, 73])

In [46]:
np.put(a,[0,1],[110,530])        # np.put(array,[index],[new_number])

In [95]:
a

array([110, 530,  70,  22,  11,  99,  51,  69,  49,  27,  33,  30,  96,
         1,  73])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis. 

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [47]:
# code
a

array([110, 530,  70,  22,  11,  99,  51,  69,  49,  27,  33,  30,  96,
         1,  73])

In [48]:
np.delete(a,[0,2,4])        # np.delete(a,[indices to delete])

array([530,  22,  99,  51,  69,  49,  27,  33,  30,  96,   1,  73])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [49]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [50]:
np.intersect1d(m,n)        # items that are in n but not in m

array([3, 4, 5])

In [51]:
np.setdiff1d(n,m)         # items that are in n but not in m

array([6, 7])

In [52]:
np.setxor1d(m,n)              # union - intersection

array([1, 2, 6, 7])

In [53]:
m[np.in1d(m,1)]              # it checks that given set has item or not eg ., here we checked that "1" is there in "m" or not 

array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [96]:
# code
a

array([110, 530,  70,  22,  11,  99,  51,  69,  49,  27,  33,  30,  96,
         1,  73])

In [97]:
np.clip(a,a_min=25,a_max=75)        # numbers < 25 will be replaces by 25 and number sgreater than 75 will be replaces by 75 


array([75, 75, 70, 25, 25, 75, 51, 69, 49, 27, 33, 30, 75, 25, 73])

In [56]:
# 17. np.swapaxes

In [57]:
# 18. np.uniform

In [58]:
# 19. np.count_nonzero

In [59]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [60]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [61]:

# 25. np.allclose and equals